kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      # serviceAccountName: spark-worker-role
      containers:
        - name: spark-worker
          image: easoncao/spark-hadoop:2.2.1
          imagePullPolicy: Always
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
