kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: LoadBalancer
  ports:
    - name: webui
      port: 80
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    component: spark-master
